pmd_beamphysics/interfaces/elegant.py
elegant and openpmd expect column p to have units="m$be$nc"
=> add correct units to column p

pmd_beamphysics/interfaces/genesis.py
This adds a function `genesis2_dpa_to_data` to process genesis2 dpa data into data for a ParticleGroup object.
=> Add genesis2_dpa_to_data

pmd_beamphysics/interfaces/gpt.py
Fix asset statement to allow weights to be >= 0 when interfacing to GPT
=> Allow weights to be = 0

pmd_beamphysics/fields/analysis.py, pmd_beamphysics/particles.py
This adds an additional `track_field_1df` that is similar to `track_field_1d`, except that it uses a function Ez_f that the user provides. The default method is set to `'RK23'`, which seems to perform better in practical examples.
=> Add track_field_1df

pmd_beamphysics/interfaces/simion.py, pmd_beamphysics/writers.py
Removes np.complex from `writers.py` as this alias is deprecated, replaced with `complex`.
=> Remove np.complex (depreciated) 

pmd_beamphysics/interfaces/genesis.py
This fixes a bug where zero current slices were ignored.
=> Fix importing Genesis4 with zero current slices

pmd_beamphysics/interfaces/genesis.py, pmd_beamphysics/particles.py, pmd_beamphysics/statistics.py
Previously `write_genesis4_distribution` was incorrectly resampling with weights for export. Genesis4 requires equal weights for this type of distribution. This PR:
- adds `equal_weights` option to `ParticleGroup.resample`, defaulting to False.
- Corrects `write_genesis4_distribution` to use this.
=> Add equal_weights option to resample, fix Genesis4 bug

pmd_beamphysics/interfaces/gpt.py
This PR opens up the allowed particle species that can be written in GPT format.  This list supported by ParticleGroup is electron, positron, and proton.
This was tested with the devel version of Lume-GPT by creating a single electron, positron, and proton - all of which given a total momentum of 1 GeV/c.  The particles were then tracked through a bending magnet with radius 1 meter (at 1 GeV/c momentum):
Each particle was then tracked using GPT.  We expect the electron to bend up, and the others to bend down, all with the same radius.  We also expect the proton to travel less distance in the same amount of time:
Loading the particles verifies the correct dynamical variables:
=> Fixed writing particle data to gpt format, tested with tracking

pmd_beamphysics/interfaces/impact.py, pmd_beamphysics/particles.py, pmd_beamphysics/tools.py, pmd_beamphysics/units.py
* `np.string_` recommends changing to `np.bytes_`
* `ndarray.ptp()` -> `np.ptp(ndarray)`
[numpy 2.0](https://numpy.org/doc/stable/release/2.0.0-notes.html#deprecations)
=> FIX: address np.string_ and ndarray.ptp deprecations in numpy 2.0

pmd_beamphysics/species.py
This PR adds the molecular hydrogen ion to the species list(s) for ParticleGroup.  The ion consists of two protons and one electron:
```
mH2pc2 = 2*mpc2 + mec2 # Molecular Hydrogen Ion H2+
e_charge = scipy.constants.e
c_light = scipy.constants.c
CHARGE_OF = {'electron': -e_charge,
'positron': e_charge,
'proton': e_charge,
'H-': -e_charge,
'H2+': e_charge,
}
CHARGE_STATE = {
'electron': -1,
'positron': 1,
'proton': 1,
'H-': -1,
'H2+': +1,
}
MASS_OF = {'electron': mec2,
'positron': mec2,
'proton': mpc2,
'H-': mhmc2,
'H2+': mH2pc2,
}
```
This seems to respect the standard:
https://github.com/openPMD/openPMD-standard/blob/upcoming-2.0.0/EXT_SpeciesType.md
=> Update species for H2+

pmd_beamphysics/species.py
This PR adds the particles "muon" and "antimuon" as options for the species of a `ParticleGroup` object. Their mass and change were added to the file `pmd_beamphysics\species.py` and the changes were tested by running some of the example notebooks with the species of the particles manually set to "muon" and "antimuon".
=> Add "muon" and "antimuon" as Valid Species for `ParticleGroup`

pmd_beamphysics/fields/analysis.py
Migration guide: https://numpy.org/doc/stable/numpy_2_0_migration_guide.html
* `np.trapz` -> `np.trapezoid`
=> FIX: numpy2 support

pmd_beamphysics/fields/analysis.py, pmd_beamphysics/labels.py, pmd_beamphysics/particles.py
Addresses the following:
```
pmd_beamphysics/fields/analysis.py:18:13: W605 invalid escape sequence '\i'
pmd_beamphysics/fields/analysis.py:67:33: W605 invalid escape sequence '\s'
pmd_beamphysics/fields/analysis.py:71:13: W605 invalid escape sequence '\R'
pmd_beamphysics/fields/analysis.py:71:22: W605 invalid escape sequence '\e'
pmd_beamphysics/fields/analysis.py:71:30: W605 invalid escape sequence '\o'
pmd_beamphysics/fields/analysis.py:193:33: W605 invalid escape sequence '\s'
pmd_beamphysics/fields/analysis.py:197:13: W605 invalid escape sequence '\R'
pmd_beamphysics/fields/analysis.py:197:22: W605 invalid escape sequence '\e'
pmd_beamphysics/fields/analysis.py:197:30: W605 invalid escape sequence '\o'
pmd_beamphysics/labels.py:125:18: W605 invalid escape sequence '\m' …
```
=> FIX: syntax warnings with unsupported escape sequences

pmd_beamphysics/interfaces/impact.py
Previously these were flagged as NotImpementedError, but that didn't belong here.
=> Enable Impact-T x_offset, y_offset

docs/examples/fields/field_examples.ipynb, environment.yml, pmd_beamphysics/fields/fieldmesh.py, tests/test_fieldmesh.py
It also refactors some of the convenience methods in `FieldMesh`:
- add `FieldMesh.xmin`, `FieldMesh.ymin`, etc.
- add `FieldMesh.xmax`, `FieldMesh.ymax`, etc.
- add setters for these.
=> Add convenience min, max properties to FieldMesh

pmd_beamphysics/particles.py
This currently fails due to the `isinstance(path, str)` check
=> ENH/FIX: support pathlib.Path for ParticleGroup filenames

docs/examples/particle_examples.ipynb, pmd_beamphysics/particles.py, tests/test_particlegroup.py
Fractional split will use weights to partition the particles:
This is useful for splitting particles into head, core, and tail parts. Here, the 5% of the charge is in the tail, 90% is in the core, and 5 % is in the head:
=> Add fractional_split method

docs/examples/labels.ipynb, docs/examples/particle_examples.ipynb, docs/examples/units.ipynb, pmd_beamphysics/labels.py, pmd_beamphysics/particles.py, pmd_beamphysics/plot.py, pmd_beamphysics/units.py, tests/test_particlegroup.py
This adds a new `z/c` key to divide by the speed of light. For example:
```
>>> P['sigma_z/c']
np.float64(2.4466662134476153e-14)
```
Units are correctly handled:
```
>>> P.units('sigma_z/c')
pmd_unit('s', 1, (0, 0, 1, 0, 0, 0, 0))
```
This is useful when particles are in t-coordinates, but you want to see a current profile in A:
This way the "head" is on the right.
=> Divide by c option 

pyproject.toml
* Removes `options.zip_safe` (wrong section / deprecated) and `options.include_package_data` (wrong section and now the default anyway)
* Reformats the pyproject.toml file as well for good measure
=> BLD: remove deprecated/invalid options in pyproject

pmd_beamphysics/interfaces/impact.py
```python
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
=> FIX: np.float deprecated in 1.2 and removed in 2

pmd_beamphysics/plot.py, tests/conftest.py, tests/test_particlegroup.py
Show a plot rather than crashing when using plot functions on `ParticleGroup` instances holding a single particle.
These are not terribly useful plots, of course, but are better than a crash.
Before
After
=> FIX: show a plot rather than crashing with single particles

mkdocs.yml, pmd_beamphysics/units.py, tests/test_unit.py
I set out to just make `pmd_unit` hashable, but got carried away with some clean-ups along the way.
* `pmd_unit` is now hashable. This means it can be used as a dictionary key or as an element of a set, for example.
* Bonus: added docstrings to some functions missing them
* Bonus: added some type hints and unit tests for `pmd_beamphysics.units`
* Bonus: added support for `*` and `/` operators of 2+ units with a couple simple tests
* Test coverage of `pmd_beamphysics.units` is now pretty good
* Fix mkdocs building after (likely) changes in mkdocstrings-python and our config. This may need to be propagated to other projects.
=> ENH: `pmd_unit` hashability
